export const ConfigKeys = {
    wordPatterns: 'cc-completion.wordPatterns',
    Ghost: {
        enabled: 'cc-completion.ghost.enabled',
        baseUrl: 'cc-completion.ghost.baseUrl',
        stops: 'cc-completion.ghost.stops',
        apiKey: 'cc-completion.ghost.apiKey',
        model: 'cc-completion.ghost.model',
        endpoint: 'cc-completion.ghost.endpoint',
        promptTemplate: 'cc-completion.ghost.promptTemplate',
        maxOutputTokens: 'cc-completion.ghost.capabilities.limits.max_output_tokens',
        maxContextWindowTokens: 'cc-completion.ghost.capabilities.limits.max_context_window_tokens',
        delay: 'cc-completion.ghost.capabilities.limits.delay',
        suffixOverlapThreshold: 'cc-completion.ghost.suffixOverlapThreshold',
        suffixOverlapType: 'cc-completion.ghost.suffixOverlapType',
        presencePenalty: 'cc-completion.ghost.presencePenalty',
        frequencyPenalty: 'cc-completion.ghost.frequencyPenalty',
        stream: 'cc-completion.ghost.stream',
    },
    Nes: {
        enabled: 'cc-completion.nes.enabled',
        baseUrl: 'cc-completion.nes.baseUrl',
        apiKey: 'cc-completion.nes.apiKey',
        model: 'cc-completion.nes.model',
        family: 'cc-completion.nes.family',
        endpoint: 'cc-completion.nes.endpoint',
        maxOutputTokens: 'cc-completion.nes.capabilities.limits.max_output_tokens',
        maxContextWindowTokens: 'cc-completion.nes.capabilities.limits.max_context_window_tokens',
        thinking: 'cc-completion.nes.capabilities.supports.thinking',
        reasoningEffort: 'cc-completion.nes.capabilities.supports.reasoning_effort',
        suffixOverlapThreshold: 'cc-completion.nes.suffixOverlapThreshold',
        suffixOverlapType: 'cc-completion.nes.suffixOverlapType',
        presencePenalty: 'cc-completion.nes.presencePenalty',
        frequencyPenalty: 'cc-completion.nes.frequencyPenalty',
        stream: 'cc-completion.nes.stream',
        nextCursorPredictionEnabled: 'cc-completion.nes.nextCursorPrediction.enabled',
        mimicGhostTextBehavior: 'cc-completion.nes.mimicGhostTextBehavior',
        promptTemplate: 'cc-completion.nes.promptTemplate',
    }
} as const;
